name: Actions Workflow

on:
  repository_dispatch:

  # schedule:
  #   - cron: "*/5 * * * *"
  #   - cron: "*/6 * * * *"
  # push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        # better to choose a specific version or commit will ensure consistency
        uses: actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b
        with:
          who-to-greet: Johnny
      - name: Save state
        run: |
          echo "{time}=${{ steps.greet.outputs.time }}" >> $GITHUB_ENV 
      - name: Log Greeting Time
        run: echo ${{ env.time }}