name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:16-bullseye-slim
    steps:
      - name: Log Node Version
        run: |
          node -v
          cat /etc/os-release

