name: matrix

on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest] 
        # also macos-latest, windows-latest... avoiding any licensing costs here
        node_version: [6,8,10]
      
      # fail-fast: true
      # max-parallel: 2
      
    runs-on: ${{ matrix.os }} 
    steps:
      - name: Log Node Version
        run: node -v
      - name: choose my own node version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }} # 6 <- example of a hardcoding
      - name: Log My Node Version
        run: node -v
      