name: Shell Commands

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    # github will cancel after 6 hours
    timeout-minutes: 360 # default is 360
    steps:
      - name: echo a string!
        run: echo "Hello world"
        # defaults to false
        # will trip all subsequent steps even if this step fails
        continue-on-error: true
        timeout-minutes: 10
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  runs-windows-commands:
    runs-on: windows-latest
    needs: [run-shell-command]
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash


